### ISSUE TITLE
Build fails with nonce<1.0.5

### ISSUE THREAD

**Issue by Yuras** [mongodb-haskell/mongodb#90]
#89 introduced `withGenerator`, which was available since `nonce-1.0.5`. Could we please also update the lower bound on `nonce` for the already released `mongoDB-2.3.0.5` on Hackage? @VictorDenisov I beleive you are the one who has permissions to do that. Thank you.

**Comment by VictorDenisov** [comment]
Thanks, I'll update it promptly.

**Comment by VictorDenisov** [comment]
Done

**Comment by Yuras** [comment]
Thank you! But looks like you forgot to update the source code itself to make sure the next release will have the correct lower bound on `nonce`. (Sorry for confusing issue description, you probably got the impression that only the bound on Hackage needed to be updated.)

**Comment by VictorDenisov** [comment]
Yeah, I was too exited that I can fix it in place and forgot about source. Pushed the fix. Thanks.
